-- ═══════════════════════════════════════════════════════════════════════════════
-- pending_reports — INSERT policy: RETRACTED 2026-09-07, see below for why
--
-- ⚠️ This file originally added a fully-open `for insert with check (true)` policy. It was
-- run, then RETRACTED THE SAME DAY once a live-measurement pass this table already had a
-- separate `tenant_insert` policy (schema-multitenant-phase2-rls.sql's generic per-table
-- template: `for insert with check (tenant_id = public.current_tenant_id())`) plus a
-- `tenant_id` column defaulting to the single-tenant UUID
-- (schema-multitenant-phase1.sql). That means a REAL, logged-in user's manual upload should
-- already pass RLS via `tenant_insert` — `current_tenant_id()` resolves the caller's tenant
-- from `profiles` via `auth.uid()`, which only works for an authenticated request.
--
-- The original diagnosis (this file's prior body, and the changelog/backlog entries that cited
-- it) tested ONLY with a bare anon key and no user session — i.e. as a logged-out visitor, not
-- as the app's real authenticated upload path. That is a different, weaker test than what
-- production actually does, and the "no INSERT policy exists at all" claim it produced was
-- wrong: `tenant_insert` was there the whole time, just invisible to an unauthenticated probe.
--
-- The policy this file added was too broad regardless (it let a fully anonymous, logged-out
-- request write rows — real exposure, not just noise) AND, oddly, a fresh live re-test even
-- after confirming it existed still returned the same RLS violation for the anon-key probe —
-- unresolved, and not worth chasing further with unauthenticated `curl` against the new opaque
-- `sb_publishable_...` key format, which may not map to the `anon` role the same way the old
-- JWT-based anon key did. The reliable next step is a REAL logged-in upload through the app
-- itself, not more synthetic probing.
--
-- Run this to remove the policy this file added:
--
--   drop policy "pending_reports: public insert" on public.pending_reports;
--
-- If a real, logged-in manual upload is later found to still fail to sync across devices, the
-- next diagnosis has to start from an authenticated session (real magic-link login), not the
-- anon key — this file's original methodology is exactly what to avoid repeating.
-- ═══════════════════════════════════════════════════════════════════════════════
