// @ts-nocheck
// #230 — the ONE changelog entry App.js needs synchronously: the latest version+date, for the
// footer text ('Meridian. v'+MERIDIAN_VERSION) and window.__MERIDIAN_VERSION__. Deliberately
// standalone — does NOT import from changelog-data.js, and is not imported by it — so App.js's
// static import of this file stays tiny regardless of how large the full changelog grows. The
// full history (including this same entry, duplicated) lives in changelog-data.js, read only by
// the lazy-loaded changelog-panel.js. See changelog-data.js's header for why the two must not
// share a module. Keeping this in sync with changelog-data.js's newest entry is mechanical —
// update both in the same commit — and guarded by src/__tests__/changelog-version.test.js.
export const LATEST_CHANGELOG_ENTRY = {version:'5.029', date:'2026-08-16', changes:[
  'Issue #358 -- two owner-reported Projections bugs, diagnosed together. (1) The row Lock button could never fully lock a week: lockRow/approveRow called setOverride 7x in a synchronous loop, each rebuilding `next` from the same stale lockedProjections prop and saving immediately -- last write won, only the final day survived, so allLocked (which requires every day) never flipped and the button stayed stuck on "Lock" no matter how many times it was clicked. approveRow had the same defect, and was additionally unreachable from the UI -- the button\'s condition was inverted (allApproved?approveRow:lockRow instead of allLocked?approveRow:lockRow), so approveRow only ever fired once a row was already approved. Fixed both to build one `next` map across all days and save once, matching showLockFor/showMonthLockFor\'s already-correct pattern; fixed the inverted condition so Lock-then-Approve is a real two-step progression.\n\n(2) Month view\'s store table had width:\'100%\' with no minWidth inside its overflowX:\'auto\' wrapper -- the same #192-class defect guarded elsewhere, but unguarded here because the guard test\'s scan matches a literal \'table\' string (this file uses the tbl() alias) and only scans 600 chars forward (this table sits ~85 lines past its wrapper). Fixed with width:\'max-content\'+minWidth:\'100%\'. A second, more likely mechanism for "can\'t scroll the monthly view" specifically -- a nested 240px-scrollable pace section pushed into the middle of the viewport by month-only content above it -- was diagnosed but NOT changed pending one repro detail from the owner, since the component\'s own docs mark its current behavior as correct for this exact call-site shape; flipping it without confirming what\'s actually being scrolled would be a guess, not a fix.\n\nNo new automated test -- projections.js has no existing test harness and lockRow/approveRow are closures over component state, not extractable as pure functions without a larger refactor; verification is manual (owner, per the issue\'s checklist).\n\n1390/1390 tests pass (no regressions), build clean (508.07 KB gzip eager, 341.93 KB headroom).',
  ]};
