// @ts-nocheck
// #230 — the ONE changelog entry App.js needs synchronously: the latest version+date, for the
// footer text ('Meridian. v'+MERIDIAN_VERSION) and window.__MERIDIAN_VERSION__. Deliberately
// standalone — does NOT import from changelog-data.js, and is not imported by it — so App.js's
// static import of this file stays tiny regardless of how large the full changelog grows. The
// full history (including this same entry, duplicated) lives in changelog-data.js, read only by
// the lazy-loaded changelog-panel.js. See changelog-data.js's header for why the two must not
// share a module. Keeping this in sync with changelog-data.js's newest entry is mechanical —
// update both in the same commit — and guarded by src/__tests__/changelog-version.test.js.
export const LATEST_CHANGELOG_ENTRY = {version:'5.027', date:'2026-08-16', changes:[
  'Issue #340 -- At A Glance reported Sales vs LY -36.16% and Guest Count vs LY -34.14% with a red "Attention" flag, and both are artifacts, not a real decline. Measured directly from qsr_daily_activity_rollup before touching any code, per the standing rule: Aug 3-11 averaged ~$289K/day, Aug 12-15 averaged ~$286K/day -- flat, matching the separate 6-week trend view\'s own +0.5%-ish reading for the same complete weeks. All 27 stores present every date in that window. Cross-checked the tile\'s own raw total against the same table: DAR holds $1,211,724 for Aug 12-16, the tile displays $934,676 -- a ~23% understatement, not a comp-math error. $934,676 / $1,211,724 = 77.1%, suspiciously close to 21/27 = 77.8% -- salesSec\'s totSales (at-a-glance.js, ~line 860) sums per store via allLocs.reduce(...byLoc(l)...), and byLoc filters labInRange by an exact string loc match; a DAR loc that fails to match any allLocs entry silently contributes zero rather than erroring, so it vanishes from the tile while a raw SQL count still includes it. That is the leading, UNCONFIRMED lead this PR does NOT chase -- the owner has explicitly tabled the underlying fix behind the At A Glance UI redesign (#340 itself), and re-deriving it here would risk exactly the kind of unverified \'probably fixed\' claim the standing rules exist to prevent.\n\nWhat this PR does instead: suppress the Sales vs LY and Guest Count vs LY comparison lines (plus the avg-check-vs-LY figure, which shares the same suspect mCurS/mCurG legs) everywhere they render -- the Sales tile header pill and Net Sales sub-line (with the OK/FL MktBadge split), the Intelligence Summary\'s two comp signal rows (relabeled \'Sales (Period)\' / \'Guest Count (Period)\' while suppressed, since a \'vs LY\' label next to a dash reads as broken rather than intentionally off), and the District Pulse Radar\'s \'Sales vs LY\' wedge (not named in the issue, but the identical value feeding a near-zero score there is exactly the same false alarm one click over -- leaving it lit would have left the fix half-done). Raw totals (net sales, guest count, avg check) are UNCHANGED and still shown -- they\'re mildly low per the ~23% gap above but still useful, per the owner\'s explicit instruction not to blank the whole tile.\n\nDone via a single module-level flag, SHOW_VSLY_COMP_340 (at-a-glance.js, near the top of the file, comment documents the full finding) -- every suppression site reads this one constant, so re-enabling once #340\'s root cause actually ships a fix is a one-line flip, not a re-implementation. A wrong number that\'s trusted is worse than no number: a blank tile reads as \'no data\' and nobody acts on it, but a red -36.16% Attention flag on the headline metric is the kind of number that starts phone calls to GMs about a collapse that never happened.\n\n1379/1379 tests pass, build clean, no bundle-size impact (conditional rendering in an already-loaded module).',
  ]};
