// @ts-nocheck
// #230 — the ONE changelog entry App.js needs synchronously: the latest version+date, for the
// footer text ('Meridian. v'+MERIDIAN_VERSION) and window.__MERIDIAN_VERSION__. Deliberately
// standalone — does NOT import from changelog-data.js, and is not imported by it — so App.js's
// static import of this file stays tiny regardless of how large the full changelog grows. The
// full history (including this same entry, duplicated) lives in changelog-data.js, read only by
// the lazy-loaded changelog-panel.js. See changelog-data.js's header for why the two must not
// share a module. Keeping this in sync with changelog-data.js's newest entry is mechanical —
// update both in the same commit — and guarded by src/__tests__/changelog-version.test.js.
export const LATEST_CHANGELOG_ENTRY = {version:'4.996', date:'2026-08-12', changes:[
  'Issue #230 — MERIDIAN_CHANGELOG (366 entries, 274,943 raw chars) was landing in the entry chunk despite rendering in exactly one place, the About modal: ~98 KB gzipped in isolation, roughly 12% of the compressed entry bundle. Surfaced by the owner while measuring an unrelated PR\'s bundle delta, and it explains why #207\'s lazy-load realization ratios kept undershooting a naive prediction by ~4x — a ~275 KB blob of highly repetitive English prose dominates the chunk\'s gzip dictionary, so moving CODE out of a bundle whose compressed weight is 12% prose reclaims far less than raw-byte arithmetic suggests. #207\'s calibration was measured against a bundle this array was distorting the whole time — treat those ratios as stale; this issue doesn\'t re-derive them, just removes the distortion for whoever does next. Fixed per the issue\'s own preferred option (1: own module + dynamic import), with one refinement the naive version would have gotten wrong: App.js cannot simply import {LATEST_CHANGELOG_ENTRY} from the same module that holds the full array, because a module reached by BOTH a static and a dynamic import path gets pulled into the eager entry chunk regardless of which named export is actually used — the identical INEFFECTIVE_DYNAMIC_IMPORT class of bug #207 already fixed three times this session (inventory.js/one-pager.js/above-store-onepager.js), just at the module-export level instead of the whole-file level. Split into three files instead: changelog-latest.js (LATEST_CHANGELOG_ENTRY only, ~4 KB — the one entry App.js needs synchronously for the footer text and window.__MERIDIAN_VERSION__, standalone, never touches the big array), changelog-data.js (the full MERIDIAN_CHANGELOG array, imported ONLY by the new lazy changelog-panel.js), and App.js itself (now imports exclusively from changelog-latest.js). MERIDIAN_VERSION stays fully derived, never hand-typed — changelog-version.test.js (rewritten, 8 tests) now also asserts App.js imports ONLY from changelog-latest.js and never from changelog-data.js (the exact mistake that would silently undo this fix), and byte-for-byte diffs LATEST_CHANGELOG_ENTRY against MERIDIAN_CHANGELOG[0] so the two hand-maintained copies can\'t drift — the same discipline this file already enforces for the version number itself. Consequence for every future commit: adding a changelog entry now means updating changelog-data.js (prepend) AND changelog-latest.js (replace) in the same commit, not one array-prepend — a small, bounded, and test-guarded cost, not a design nobody will remember to honor. Measured, not the isolated 98 KB figure the issue itself warned not to quote: entry chunk gzip 820.18 KB -> 721.82 KB (-98.36 KB), headroom 29.82 KB -> 128.18 KB. changelog-panel.js + changelog-data.js land in their own lazy chunk together, 269.72 KB raw / 101.08 KB gzip, never fetched unless the About modal is actually opened. 1325/1325 tests pass.',
  ]};
